spring:
  datasource:
    url: jdbc:h2:mem:auth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9090
