spring:
  datasource:
    url: jdbc:h2:mem:admin
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    jdbc-type-for-null: varchar
  type-aliases-package: me.kyuu.admin.core.mvc

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace